### PR TITLE
Views mixin

### PR DESCRIPTION
**Pull request by petrem**

### CODE REVIEW

**Comment by petrem** [comment]
Arguably it would be nicer to define the method as:
```
    def run_view(
        self,
        namespace,
        function,
        *args,
        upload=None,
        use_post=False,
        *kwargs,
    ):
    ...
```
and use `args` and `kwargs` in place of `view_args` and `view_opts`?

**Comment by petrem** [comment]
I also think I'd better respond with `response.json()` instead of `response.text`

**Comment by petrem** [comment]
Further, from /v1/views/...,  we almost always return a json of the form
```
[
    {
        "current_plugin_id_by_name_and_version": "4375bc8ec2634ba5a809a0738fc7407e"
    }
]
```
and in that case it would probably be useful to simply extract the function's result.
The exception is for views that return a CSV file. Unfortunately, unless you explicitly pass download_as, the http response gives no indication that this was the case, expcet a content-type of application/csv. I wonder if that should be the discriminator.

**Comment by tcorbettclark** [comment]
Extended approach and now and superseded by https://github.com/tcorbettclark/encapsia-api/pull/5

**Pull request closed without merging**
